### ISSUE TITLE
use cache to improve loading speed of components

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal_ui#864]
I've already done a super simple implementation of using cache on [f7eda5a](https://github.com/12rambau/sepal_ui/pull/863/commits/f7eda5a1507cd3f3a50455e92b92de26b34ef86b), instead of always instantiate `view` elements, we can store and only change them if there's a change, with this implementation, the performance of the component in terms of speed has increased up to 90%.

I think we can scale up this solution to instead of store the current elements in the object itself, we can save them into a serialized file, and not only increase the time of the component during the session but for all of them.

**Comment by 12rambau** [comment]
I see your point and that's a great idea. So you would like to apply ot every widget reloading istself ? (dropdowns, lists, etc...)

**Comment by dfguerrerom** [comment]
this cannot be done in other components...
