### ISSUE TITLE
make sepal_ui compatible with voila sepal-ui-template

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal_ui#909]
I've been working with a [voila template](https://github.com/dfguerrerom/voila-sepal-ui) to render sepal-ui based apps which has some cool features:
- Replace default jupyter spinning wheel and cell count number when loading
- Adds a kernel status icon
- Capture errors when it executes the cells and display them in a more user-friendly way
- Load app js scripts on a custom holder for scripts in the DOM (and here is where we need to add a tag to all vuetify template scripts)
- Minimize the DOM (diom).

It will also close https://github.com/12rambau/sepal_ui/issues/908 and https://github.com/12rambau/sepal_ui/issues/884

**Comment by 12rambau** [comment]
ping me again If I don't review this one before Monday
