### ISSUE TITLE
new rights 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal_ui#924]
Hi @dfguerrerom as promised I moved the rtepository to openforis organization as I have less and less time to look for it and it seems its use will remain intertwined with SEPAL itself. 

I will check along next week things that are not working and things that need to be rewired. in the meantime can you check what rights you have over the repository itself ?

**Comment by dfguerrerom** [comment]
hey @12rambau thanks for that.
I don't have full permission to use the repository. Might it be something that can be changed within the openforis org?

**Comment by dfguerrerom** [comment]
I already have requested full control of the repository to the openforis admins.
