### ISSUE TITLE
the planet version is outdated and prevent the conda-forge buid to complete

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal_ui#936]
The latest builds of the conda-forge distribution have been blocked by the planetlab version: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1009093&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

I don't remember why we pinned it to 2.7 but would it be possible to use the latest one instead (2.10) ?

**Comment by dfguerrerom** [comment]
it was pinned because of https://github.com/openforis/sepal_ui/issues/920, I will take a look.

**Comment by dfguerrerom** [comment]
I updated by mistake to v.2.20.0, but this version now has planet unpinned, and this one should now work in coda-forge
