### ISSUE TITLE
consider drop support for python 3.8?

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal_ui#942]
There's a conflict between versions of fiona/geopandas in python 3.8:
- check https://github.com/openforis/sepal_ui/actions/runs/10834406967/job/30063536755

The problem has been discussed in: https://stackoverflow.com/questions/78949093/how-to-resolve-attributeerror-module-fiona-has-no-attribute-path

I think is just matter of pin some versions with conditions?

**Comment by 12rambau** [comment]
I guess so but if the problem is only 3.8 you can drop it, it has reached EOL
