### ISSUE TITLE
copy the current status of the map object into ipygee ? 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal_ui#955]
Hi @dfguerrerom, 

I'm slowly building a jupyterlab interface for GEE based on our favorite widget package: `ipyvuetify`. 
I'm struggling a lot with the `geemap` interface that have way too many deps and don't display nicely in the sidecar. Is it ok for you if I "steal" the map we built in `sepal-ui` to copy it in the `ipygee` code source ?

**Comment by dfguerrerom** [comment]
hey @12rambau, that's ok to me. 
In the future, I could integrate that map here to also leverage the support.
